apiVersion: v1
kind: Namespace
metadata:
  name: oauth2
---
apiVersion: v1
kind: Service
metadata:
  name: fake-oauth2
  namespace: oauth2
  labels:
    app: fake-oauth2
spec:
  type: ClusterIP
  ports:
    - port: 8282
      protocol: TCP
      name: registry
      targetPort: 8282
  selector:
    app: fake-oauth2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-oauth2
  namespace: oauth2
  labels:
    app: fake-oauth2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-oauth2
  template:
    metadata:
      labels:
        app: fake-oauth2
    spec:
      containers:
        - name: fake-oauth2
          image: "afcastano/fake-oauth2:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8282
