apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFUzTVRZME9EYzVOREFlRncweE9URXdNakV3T1RBMk16UmFGdzB5T1RFd01UZ3dPVEEyTXpSYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFUzTVRZME9EYzVOREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkkrNlhKeGNPdUpmeVRSMjVzdHNZMEdVMUhjNzRuN1BNdElLOXNKK2ZhVFYKeTRya2p0eGcra211MnBtUDJqY3RCTFo5eHlMZ2RJcy9JMTV3bGRtUUJqT2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSURCZWtDZTUyUDRvCjlLL1NXSGNxd3pBSmJiUno3a2lORnFTZHNuc2xObEdSQWlBT1kxL3FlQnl3TjQ3ekN2UmNCbyt5cXVlNEZFZWQKSzZLcXZNcjBWeUpBZmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.64.2:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: ee8eae326f8f56575fc52b9c53cea0a6
    username: admin
