spring:
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: ${user.home}/config
          - type: git
            uri: https://github.com/spring-cloud-samples/config-repo.git
            basedir: /tmp/config-repo
            refresh-rate: 10