spring:
  profiles:
    include: git
  cloud:
    config:
      server:
        git:
            uri: https://github.com/afcastano/spinnaker-local-dev.git
            basedir: /tmp/config-repo
            refresh-rate: 10