halyard:
  spinnakerVersion: 1.16.1
  additionalProfileConfigMaps:
    create: true
    data:
      spinnakerconfig.yml: |-
        spring:
          profiles:
            include: git
          cloud:
            config:
              server:
                git:
                    uri: https://github.com/afcastano/spinnaker-local-dev.git
                    basedir: /tmp/config-repo
                    refresh-rate: 10
      gate-local.yml: |-
        server:
          tomcat:
            protocolHeader: X-Forwarded-Proto
            remoteIpHeader: X-Forwarded-For
            internalProxies: .*
        # security:
        #   oauth2:
        #     client:
        #       clientId: dummy-client-id
        #       clientSecret: dummy-client-secret
        #       userAuthorizationUri: http://192.168.0.4:8282/auth/request/path
        #       accessTokenUri: http://192.168.0.4:8282/access/token/request
        #       scope: []
        #     resource:
        #       userInfoUri: http://192.168.0.4:8282/userInfo
        #     userInfoMapping:
        #       email: email
        #       firstName: name
        #       lastName: name
        #       username: name
